version: '3'
services:
    postgres:
        container_name: complex-postgres
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        container_name: complex-redis
        image: redis:latest
    nginx:
        container_name: complex-nginx
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - 3050:80
        depends_on: 
            - api
            - client
    api:
        container_name: complex-api
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on:
            - postgres
    client:
        container_name: complex-client
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        container_name: complex-worker
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            
            